#설정값

# OAuth2.0 로그인

#네이버
naver.client.id=B5n1p9KhSRITN5ISiahO
naver.client.secret=G_jNma7N89
naver.redirect.uri=http://localhost:8080/lib-sys/naverCallback.do

#카카오
kakao.clinet.id=881a98f9129ea13bd0d4552544e23944
kakako.client.secret=0n24kwpEUprDaVGJTdsc2REdqeZexCbZ
kakao.redirect.uri=http://localhost:8080/lib-sys/kakakoCallback.do