-- HSQLDB initialization script for Library Management System
-- Auto-executed by Spring when spring.datasource.initialization-mode=always

CREATE TABLE IF NOT EXISTS MEMBER (
    MEMBER_ID     INTEGER IDENTITY PRIMARY KEY,
    LOGIN_ID      VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD      VARCHAR(255) NOT NULL,
    NAME          VARCHAR(100) NOT NULL,
    EMAIL         VARCHAR(100),
    PHONE         VARCHAR(20),
    IS_ADMIN      BOOLEAN DEFAULT FALSE,
    CURRENT_LOAN_CNT INTEGER DEFAULT 0,
    MEMBER_STATUS   INTEGER DEFAULT 1,
    MEMBER_REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CATEGORY (
    CATEGORY_ID   INTEGER IDENTITY PRIMARY KEY,
    CATEGORY_CODE INTEGER NOT NULL UNIQUE,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION   VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS BOOK (
    BOOK_ID       INTEGER IDENTITY PRIMARY KEY,
    TITLE         VARCHAR(200) NOT NULL,
    AUTHOR        VARCHAR(100),
    PUBLISHER     VARCHAR(100),
    CATEGORY_CODE INTEGER,
    BOOK_DESC     VARCHAR(2000),
    TOTAL_CNT     INTEGER DEFAULT 0,
    CURRENT_CNT   INTEGER DEFAULT 0,
    DAMAGED_CNT   INTEGER DEFAULT 0,
    BOOK_REG_DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS LOAN (
    LOAN_ID      INTEGER IDENTITY PRIMARY KEY,
    MEMBER_ID    INTEGER NOT NULL,
    BOOK_ID      INTEGER NOT NULL,
    LOAN_DATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DUE_DATE     TIMESTAMP,
    RETURN_DATE  TIMESTAMP,
    STATUS       VARCHAR(20) DEFAULT 'ACTIVE'
);

CREATE TABLE IF NOT EXISTS RESERVATION (
    RESERVATION_ID   INTEGER IDENTITY PRIMARY KEY,
    MEMBER_ID        INTEGER NOT NULL,
    BOOK_ID          INTEGER NOT NULL,
    RESERVATION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS           VARCHAR(20) DEFAULT 'PENDING'
);

CREATE TABLE IF NOT EXISTS REVIEW (
    REVIEW_ID      INTEGER IDENTITY PRIMARY KEY,
    MEMBER_ID      INTEGER NOT NULL,
    BOOK_ID        INTEGER NOT NULL,
    RATING         INTEGER,
    CONTENT        VARCHAR(1000),
    REVIEW_REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Sample data
INSERT INTO CATEGORY (CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION) VALUES (1, '소설', '문학 소설');
INSERT INTO CATEGORY (CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION) VALUES (2, '교양', '일반 교양서');
INSERT INTO CATEGORY (CATEGORY_CODE, CATEGORY_NAME, DESCRIPTION) VALUES (3, '전문서', '전문 분야 서적');

INSERT INTO MEMBER (LOGIN_ID, PASSWORD, NAME, EMAIL, PHONE, IS_ADMIN, CURRENT_LOAN_CNT, MEMBER_STATUS)
VALUES ('admin', 'admin123', '관리자', 'admin@lms.com', '010-0000-0000', TRUE, 0, 1);

INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHER, CATEGORY_CODE, BOOK_DESC, TOTAL_CNT, CURRENT_CNT)
VALUES ('스프링 활성화', '전광규', '어크로스', 3, '스프링 프레임워크 활용 가이드', 5, 5);

INSERT INTO BOOK (TITLE, AUTHOR, PUBLISHER, CATEGORY_CODE, BOOK_DESC, TOTAL_CNT, CURRENT_CNT)
VALUES ('자바의 정석', '남궁성', '도우출판', 3, 'Java 프로그래밍 입문서', 10, 10);
